#1. Create a 3x3x3 array with random values

In [6]:
import numpy as np
np.random.randn(3,3,3)


array([[[ 0.76407344,  0.63531495,  0.35804775],
        [-0.92046071,  0.5650225 ,  1.44229423],
        [-1.06317931,  1.15147557,  0.18989581]],

       [[-1.27537869,  0.91096169,  0.6686835 ],
        [ 0.676969  , -0.17139669, -0.72334944],
        [-0.29328097, -1.81893925, -0.14951737]],

       [[-0.4941128 ,  0.07425907, -1.35309265],
        [ 0.01812337, -0.9935258 ,  1.50156276],
        [-1.69293553,  0.29890093, -1.08422898]]])

 # 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
b=[1,2,3,4]
a= np.diag(b , k = -1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [ ]:
import numpy as np
x= np.ones((3,3))
print("checkerboard pattern is::")
x= np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

checkerboard pattern is::
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#4.Normalize a 5x5 random matrix

In [ ]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)


Original Array:
[[0.92702256 0.91071644 0.58930231 0.29337019 0.41264928]
 [0.68338815 0.94066278 0.51036358 0.94874367 0.54963949]
 [0.36773321 0.46577397 0.04318752 0.00760943 0.2865082 ]
 [0.44800459 0.65825207 0.71611268 0.44113013 0.72774695]
 [0.71708648 0.159147   0.06117727 0.63062843 0.40408629]]
After normalization:
[[0.97692029 0.95959426 0.61807643 0.30363443 0.43037416]
 [0.71804711 0.99141367 0.53420026 1.         0.57593279]
 [0.38264869 0.48682167 0.03780342 0.         0.29634325]
 [0.46794086 0.69133883 0.75281849 0.46063641 0.76518046]
 [0.75385319 0.16101589 0.05691839 0.66198739 0.42127557]]


 # 5. How to find common values between two arrays?

In [ ]:
import numpy as np
array1 = np.array([0, 5, 10, 15, 20])
print("Array1: ",array1)
array2 = np.array([5, 15, 25])
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))



Array1:  [ 0  5 10 15 20]
Array2:  [ 5 15 25]
Common values between two arrays:
[ 5 15]


# 6.How to get the dates of yesterday, today and tomorrow?

In [10]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [11]:
import numpy as np
a=np.array([[1, 2, 3],[1, 2, 3]])
b=np.array([[1, 2, 3],[1, 2, 3]])

comparison = a==b
print("comparison")
print(comparison)
overall = comparison.all()
print("overall :",overall)


comparison
[[ True  True  True]
 [ True  True  True]]
overall : True


 # 8.Create random vector of size 10 and replace the maximum value by 0 

In [ ]:
import numpy as np
x = np.empty(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.         0.         0.         0.         0.         0.
 0.         0.         0.05149998 0.        ]
Maximum value replaced by 0:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 9. How to print all the values of an array?

solution: By using function print(arrayname)

In [ ]:
import numpy as np
array1 = np.array([10, 20, 30, 40, 50])
print(array1)

[10 20 30 40 50]


 # 10.Subtract the mean of each row of a matrix

In [12]:
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

col= np.mean(a,axis=0)
row= np.mean(a,axis=1)
print("col:",col)
print("row:",row)

sub=0
for i in row:
            sub= i-sub

            print(sub)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
col: [4. 5. 6.]
row: [2. 5. 8.]
2.0
3.0
5.0


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [13]:
v1=np.array([1,2,3,4,5])

i= np.random.randint(0,len(v1),20)
print("indices",i)
np.add.at(v1,i,1)

print("v1 after adding 1 at indices",v1)

indices [0 3 3 0 4 0 1 4 0 2 0 1 3 2 4 3 2 2 2 4]
v1 after adding 1 at indices [6 4 8 8 9]


# 12.How to get the diagonal of a dot product?

In [14]:
import numpy as np
matrix1=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2=np.array([[10,20,30],[40,50,60],[70,80,90]])

a= matrix1.dot(matrix2)
print(a)

print("diagonal of dot product \n",np.diag(a))

[[ 300  360  420]
 [ 660  810  960]
 [1020 1260 1500]]
diagonal of dot product 
 [ 300  810 1500]


# 13.How to find the most frequent value in an array?

In [ ]:
import numpy as np
x = np.random.randint(0, 10, 40)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 4 8 1 6 4 9 9 1 7 8 4 8 4 5 9 9 9 5 0 1 2 8 5 7 8 9 8 6 1 8 8 9 1 2 8 2
 3 0 4]
Most frequent value in the above array:
8


# 14.How to get the n largest values of an array

In [15]:
import numpy as np
x = np.arange(10)
print("Original array:")
print(x)

print ("Largest value is:",max(x))

Original array:
[0 1 2 3 4 5 6 7 8 9]
Largest value is: 9


# 15.How to create a record array from a regular array?

In [ ]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])


(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
